### ISSUE TITLE
LIS2DH12 STdC driver read: Read, auto increment bits - are not set

### ISSUE THREAD

**Issue by ojousima** [STMicroelectronics/STMems_Standard_C_drivers#1]
# Description
When integrating LIS2DH12 driver to my project, I have to define platform read function as 
```
int32_t spi_stm_platform_read(void* dev_id, uint8_t reg_addr, uint8_t *data,
                              uint16_t len)
{
  uint8_t ss = *(uint8_t*)dev_id;
  // bit 0: READ bit. The value is 1.
  // bit 1: MS bit. When 0, does not increment the address; when 1, increments the address in
  // multiple reads.
  uint8_t read_cmd = reg_addr | 0x80;
  if(len > 1) { read_cmd |= 0x40; }
  return spi_platform_read(ss, read_cmd, data, len);
}
```

because the driver does not set appropriate bit flags when reading registers. 

# Proposed fix:
Implement `int32_t lis2dh12_read_reg` as
```
int32_t lis2dh12_read_reg(lis2dh12_ctx_t* ctx, uint8_t reg, uint8_t* data,
                          uint16_t len)
{
  uint8_t read_cmd = reg | 0x80;
  if(len > 1) { read_cmd |= 0x40; }
  return ctx->read_reg(ctx->handle, read_cmd, data, len);
}
```

# Action
Would you accept pull request for the change if I opened one?
I'm fine with assigning copyrights of contribution to you under any MIT-compatible license in case your legal department asks :)

**Comment by albezanc** [comment]
Proposed fix is valid only for SPI case: the multiple access flag position is related to the used interface (I2C or SPI). The driver is independent of the interface, for this reason the flag should be manage by the user in the platform functions as showed in the example code (\example\read_data_simple.c) 

Thanks for your contribution.
