### ISSUE TITLE
driver for LSM9DS1 for the STM32F4 series

### ISSUE THREAD

**Issue by SathyaPrakash0812** [STMicroelectronics/STMems_Standard_C_drivers#10]
Hi,
I'm working on a project which requires LSM9DS1 to be integrated. I saw in one of the older closed issues indicating there will be a driver releasing soon (august 16th). The issue was closed although I could not find a driver in your repo. Could you please redirect me to any Beta version for now? or may be let me know when it would be made available?

Best Regards,
Sathya

**Comment by albezanc** [comment]
As told in closed issue titled "Plans to add driver for LSM9DS1" on 31 Aug a first version will be available within the end this month ( couple of month from 31 Aug ) on this repository.

Thanks for your clarification.
