### ISSUE TITLE
lsm6dsox : compilation bug on wake_up event example

### ISSUE THREAD

**Issue by Duvalcle** [STMicroelectronics/STMems_Standard_C_drivers#101]
### Device part numbers

Only looked at "wake up" example for lsm6ds0x_wake_up.c

### Type of bug

impossible to call lsm6dsox_pin_int1_route_set as is.

Specify where the bug is found. *(ie: driver, examples, resources, etc.)*

### Describe the bug

Need to remove extra character in commented line if we want to compile this line.
Concerned file : lsm6dsox_STdC/example/lsm6dsox_wake_up.c
Concerned line : 168 
  //lsm6dsox_pin_int1_route_set(&dev_ctx, &int1_route);
If we uncomment this line to use int1 gcc reports following : 
Src/lsm6dsox_wake_up.c:138:41: error: incompatible type for argument 2 of 'lsm6dsox_pin_int1_route_set'
   lsm6dsox_pin_int1_route_set(&dev_ctx, &int1_route);
                                                                    ^

Need to replace the line with :
  //lsm6dsox_pin_int1_route_set(&dev_ctx, int1_route);

Otherwise : Thanks a lot for your excellent work around your drivers and examples !!! Really simple to port it on my Stm32wb on my custom hardware and CubeMX :+1:

**Comment by albezanc** [comment]
Thanks to you for your contribution !
