### ISSUE TITLE
lsm6dsrx_self_test

### ISSUE THREAD

**Issue by Bezalelzx** [STMicroelectronics/STMems_Standard_C_drivers#102]
### Device part numbers
lsm6dsrx

### Type of bug
examples->self test

### Describe the bug
Calling wrong data ready check function during Gyroscope Self Test. 
Should be lsm6dsrx_gy_flag_data_ready_get(&dev_ctx, &drdy) @ line 286 and 313.

### Additional context

Add any other context about the problem here. *(ie: hardware description, compiler used, etc...)*

**Comment by albezanc** [comment]
Thanks for your contribution and happy new year!
