### ISSUE TITLE
LSM303AGR - lsm303agr_xl_pin_int2_config_set() overlooked

### ISSUE THREAD

**Issue by KenSeth** [STMicroelectronics/STMems_Standard_C_drivers#11]
(https://github.com/STMicroelectronics/STMems_Standard_C_drivers/blob/f4c7f83134a2a417599a97dc37f944331c4209d3/lsm303agr_STdC/driver/lsm303agr_reg.c#L1886-L1890)
Hi, the  lsm303agr_xl_pin_int2_config_set() uses lsm303agr_read_reg() instead of lsm303agr_write_reg(). This seems to be an overlooked.

**Comment by albezanc** [comment]
sure, Thanks for your contribution.
