### ISSUE TITLE
LSM6DSO32:  LSM6DSO32_XL_GY_DRDY appear to be swapped

### ISSUE THREAD

**Issue by riyadth** [STMicroelectronics/STMems_Standard_C_drivers#112]
https://github.com/STMicroelectronics/STMems_Standard_C_drivers/blob/4050c8ff708fdab76b8907ed1f033d96c187401e/lsm6dso32_STdC/driver/lsm6dso32_reg.h#L3541

```
typedef enum {
  LSM6DSO32_EXT_ON_INT2_PIN = 0,
  LSM6DSO32_XL_GY_DRDY      = 1,
} lsm6dso32_start_config_t;
```
For proper operation of the `lsm6dso32_sh_syncro_mode_set()` API, I found that I needed a value of 0 to trigger based on the accelerometer/gyroscope data ready signal. It appears that this enumeration is incorrect with respect to the part data sheet and the hardware itself.

**Comment by albezanc** [comment]
Thank you for your contribution!
