### ISSUE TITLE
Example improvements to stts22h_STdC

### ISSUE THREAD

**Issue by uilter** [STMicroelectronics/STMems_Standard_C_drivers#115]
### Device part numbers

STTS22H.

### Type of bug

There is a misunderstood into example code.
File: STMems_Standard_C_drivers/stts22h_STdC/example/stts22h_read_data_polling.c, lines 130 and 133.

### Describe the bug

Over temperature interrupt value needs to be set following this equation:  ( degC / 0.64 ) + 64.

**Comment by uilter** [comment]
Thank you very much!

**Comment by albezanc** [comment]
You are welcome and thanks for your contribution!
