### ISSUE TITLE
iis2dlpc: Wrong temperature value

### ISSUE THREAD

**Issue by sprucify** [STMicroelectronics/STMems_Standard_C_drivers#125]
https://github.com/STMicroelectronics/STMems_Standard_C_drivers/blob/06140d1faa0a2cdc4192062abe642f61cd6aebee/iis2dlpc_STdC/driver/iis2dlpc_reg.c#L131

I think this line should divide the value an extra 16 
https://community.st.com/s/question/0D73W000000nUzb/detail?s1oid=00Db0000000YtG6&s1nid=0DB0X000000DYbd&emkind=chatterCommentNotification&s1uid=0050X000009yxXV&emtm=1619087436434&fromEmail=1&s1ext=0

**Comment by albezanc** [comment]
Thank you for your contribution!
