### ISSUE TITLE
lis25ba: uninitialized variable in function bus_mode_set

### ISSUE THREAD

**Issue by pabigot** [STMicroelectronics/STMems_Standard_C_drivers#126]
This line:

https://github.com/STMicroelectronics/STMems_Standard_C_drivers/blob/06140d1faa0a2cdc4192062abe642f61cd6aebee/lis25ba_STdC/driver/lis25ba_reg.c#L224

produces this diagnostic:

```
../subprojects/stmemsc/src/lis25ba_reg.c: In function 'lis25ba_bus_mode_get':
../subprojects/stmemsc/src/lis25ba_reg.c:208:24: error: 'tdm_cmax_l' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  208 |   lis25ba_tdm_cmax_l_t tdm_cmax_l;
```

because the value is used unconditionally even though the read of the register providing the value failed.

**Comment by albezanc** [comment]
Thank you for your contribution!
