### ISSUE TITLE
i3g4250d: incorrect multiple byte reading in i3g4250d_angular_rate_raw_get()

### ISSUE THREAD

**Issue by albatron22** [STMicroelectronics/STMems_Standard_C_drivers#135]
### Device part numbers

i3g4250d

### Type of bug

Driver. File [i3g4250d_reg.c](https://github.com/STMicroelectronics/i3g4250d/blob/master/i3g4250d_reg.c)

### Describe the bug

I found an incorrect multiple byte reading in function `int32_t i3g4250d_angular_rate_raw_get(stmdev_ctx_t *ctx, int16_t *val)`:
```
 ret =  i3g4250d_read_reg(ctx, I3G4250D_OUT_X_L, buff, 6);
```
I3G4250D datasheets [DS10938](https://www.st.com/resource/en/datasheet/i3g4250d.pdf) page 23:
> In order to read multiple bytes, it is necessary to assert the most significant bit of the subaddress field. In other words, SUB(7) must be equal to 1, while SUB(6-0) represents the address of the first register to be read.

The start address of the read (subaddress ) must be `I3G4250D_OUT_X_L | 0x80`:
```
ret = i3g4250d_read_reg(ctx, I3G4250D_OUT_X_L | 0x80, buff, 6);
```
This works in my application.

*Note*: connection interface - I2C. For transmission used `HAL function HAL_I2C_Mem_Write`

**Comment by albezanc** [comment]
Hi albatron22, the bug is in the example file, please see the commit related to this issue.
Thanks for your input, really appreciated !
