### ISSUE TITLE
lsp22ch: pressure value is only zero

### ISSUE THREAD

**Issue by alexmaron81** [STMicroelectronics/STMems_Standard_C_drivers#138]
### Device part numbers

lsp22ch

### Question

Hello.

I don't use this library, but I stuck to it.
I use an esp32 with the steval-mki219v1 development board.
At the beginning I was able to read values from the PRESS_OUT_H, PRESS_OUT_L and PRESS_OUT_XL registers, but after a short time I only get zero from these registers.
Other registers like "Who am I" still work.

Can someone tell me what it could be?

**Comment by albezanc** [comment]
Hi alexmaron81,

I think you are referring to the lps22ch pressure sensor. In any case I am sorry but this section is specifically dedicated to the support and development of platform independent C standard drivers. The right place for [ST Community Forum](https://community.st.com/s/).

My personal advice is: first check if there is a similar issue already handled by [ST Community Forum] (https://community.st.com/s/) and if not, open a new thread adding more details:
- used interface I2C/SPI and if you are using SPI specify the MODE
- interface clock frequency
- sensor configuration such as ODR, FIFO, interrupt configuration, or better a registers dump
- description of hardware connection 
- an example of code for reproducing the issue

Thanks for the opportunity for clarification.
