### ISSUE TITLE
where is the function: lis3dh_temperature_meas_set ,i cannot find it

### ISSUE THREAD

**Issue by xtaens** [STMicroelectronics/STMems_Standard_C_drivers#15]
where is the function: lis3dh_temperature_meas_set(&dev_ctx, LIS3DH_TEMP_ENABLE); ,i cannot find it
who share me 
thanks

**Comment by albezanc** [comment]
Hi xtaens,
the example `read_data_simple.c` of lis3dh is now fix: `lis3dh_temperature_meas_set` replaced with `lis3dh_aux_adc_set`.
Thanks for your contribution !

**Comment by xtaens** [comment]
thanks  albezanc
