### ISSUE TITLE
IIS3DWB code library

### ISSUE THREAD

**Issue by maygut** [STMicroelectronics/STMems_Standard_C_drivers#151]
Hi,

I am using the Steval-mki109v3 with the Steval-mki208v1 (IIS3DWB accelerometer). I wanted to the polling data example code but I am having trouble finding the tim.h file that is needed to run that code. Would you know where I can find this library?

**Comment by avisconti** [comment]
It should be automatically generated when you do "generate code" using the proper ioc file (i.e. _prj_MKI109V3/_prj_MKI109V3.ioc in your case).
