### ISSUE TITLE
Lsm6dsox devide_id_get

### ISSUE THREAD

**Issue by Furki81** [STMicroelectronics/STMems_Standard_C_drivers#152]
Hi ,
I'm doing an application which includes lsm6dsox .(Stm32cubemx,stm32cube ide, freertos-cmsis rtos-v2) . I did pin config. and try to implement your lsm6ds3_reg.h / .c driver files into my project. (according to the lsm6dsox)
When program come in device_id_get funct. it goes into "Hardfault". Can you help me at that point ? how can i solve this ?

int32_t lsm6dsox_device_id_get(lsm6dsox_ctx_t *ctx, uint8_t *buff)
{
  int32_t ret;
  ret = lsm6dsox_read_reg(ctx, LSM6DSOX_WHO_AM_I, buff, 1);
  return ret;
}

What is *buff  . İ mean which data gets or read from LSM6Dsox ?
- i can not understand *buff parameter. I get into lsm6dsox.h . But i couldnt find anything about it ?

**Comment by avisconti** [comment]
Sorry for late reply.
I just think that the API is not called properly, as you have to pass a valid buffer pointer:

```
uint8_t id;

lsm6dsox_device_id_get(ctx, &id);
```

You can take a look to [lsm6dsox_STdC/examples/lsm6dsox_read_data_polling.c](https://github.com/STMicroelectronics/STMems_Standard_C_drivers/blob/master/lsm6dsox_STdC/examples/lsm6dsox_read_data_polling.c#L145) to see how this API is used.
