### ISSUE TITLE
lsm6dsv16x: timestamp

### ISSUE THREAD

**Issue by nicogou** [STMicroelectronics/STMems_Standard_C_drivers#168]
### Device part numbers

lsm6dsv16x (at least, didn't check the others)

### Type of bug

examples/lsm6dsv16x_fifo_irq.c (at least)

### Describe the bug

When receiving a timestamp via FIFO, the printed value is in LSB, not ms as suggested by the message. In order to convert LSB to milliseconds, one needs to multiply the received value by 21.75µs (see table 127 of the datasheet).
It looks like there is a lsm6dsv16x_from_lsb_to_nsec function which converts the received timestamp to nanoseconds.

**Comment by BeSeeTek** [comment]
@nicogou regarding timing, be aware that the sensors odr is quite in accurate and unstable, see tab 3 and also there is a lot of variation between different devices, so always use external synchronization.
