### ISSUE TITLE
lsm6dsl_den_enable_set

### ISSUE THREAD

**Issue by Cyra95** [STMicroelectronics/STMems_Standard_C_drivers#24]
Hi

I've found an error in the LSM6DSL api. I tried to extend the DEN functionallity to the accelerometer with a call of lsm6dsl_den_enable_set function. 

The following code snippet is from your api function, whereas val = 2 (LSM6DSL_STAMP_IN_GY_XL_DATA). 
reg.ctrl4_c.den_xl_en = (uint8_t)val & 0x02U;

The problem is that "val & 0x02" will return 0x02 instead of 0x01 --> the bit won't get set. The code should be fixed with "val && 0x02U".

Kind regards

**Comment by albezanc** [comment]
Please update the driver: with MISRA compliance introduction the issue was fix.

Thanks for you contribution!
