### ISSUE TITLE
LSM6DS3 in Sensor hub mode : code issues

### ISSUE THREAD

**Issue by alexandrebarsacq** [STMicroelectronics/STMems_Standard_C_drivers#26]
Hi, I was looking at the code of for LSM6DS used as a sensor hub.

There must be a mistake in the [example code line 195](https://github.com/STMicroelectronics/STMems_Standard_C_drivers/blob/master/lsm6ds3_STdC/example/sensor_hub_lis2mdl_lps22hb_no_fifo_simple.c#L195) or in the structure declaration lsm6ds3_sh_read_t :  there is no .byte member in that structure. 

I believe there is another mistake in [the driver](https://github.com/STMicroelectronics/STMems_Standard_C_drivers/blob/master/lsm6ds3_STdC/driver/lsm6ds3_reg.c#L5563)  L5563 : the second read to registers should be LSM6DS3_SENSORHUB13_REG  , I believe.

Best Regards

Alexandre Barsacq

**Comment by albezanc** [comment]
You are right, lsm6ds3  sensor hub example was not updated after the "MISRA compliance" migration and, yes, there was a typo in the driver. I've just update driver and examples following your indications.

Thanks very much for your contribution!
