### ISSUE TITLE
LPS22HB lps22hb_from_lsb_to_hpa should take int32_t or uint32_t

### ISSUE THREAD

**Issue by phild68** [STMicroelectronics/STMems_Standard_C_drivers#30]
According to the register address map in the documentation of the LPS22HB there are 3 x 8 bit registers for the measured pressure output value: -

PRESS_OUT_XL (0x28) (Pressure value bits 7 to 0)
PRESS_OUT_L    (0x29) (Pressure value bits 15 to 8)
PRESS_OUT_H . (0x2A) (Pressure value bits 23 to 16)

The lps22hb_pressure_raw_get() function correctly reads the 3 consecutive addresses to retrieve the full data, however a subsequent call to lps22hb_from_lsb_to_hpa() (as per the example) only accepts a int16_t so the MSBs are lost in truncation. 

The correct function should take a uint32_t or int32_t (and probably mask off the top 8 bits)

**Comment by albezanc** [comment]
The issue is solved. Thank you for your contribution!
