### ISSUE TITLE
LSB to Celsius

### ISSUE THREAD

**Issue by mikucukyilmaz** [STMicroelectronics/STMems_Standard_C_drivers#31]
https://github.com/STMicroelectronics/STMems_Standard_C_drivers/blob/89b9c32c29aa8c64b8df62d931052a6737d046d8/lsm6ds3_STdC/driver/lsm6ds3_reg.c#L148

When converting LSB to Celsius, +16 LSB/°C sensitivity must be considered as below.

```
float_t lsm6ds3_from_lsb_to_celsius(int16_t lsb)
{
  return ((float_t)lsb/16.0f + 25.0f );
}
```

**Comment by albezanc** [comment]
Sure , thanks for your contributions
