### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by KiLuYa** [STMicroelectronics/STMems_Standard_C_drivers#37]
Do the app using on LSM6DSO can be used on LSM6DSOX without any change?

**Comment by albezanc** [comment]
The good practice is use the the driver associated to the right part number.
Typically many APIs has the same name (except the prefix) but the implementation has some differences (in your specific case the functions for manage the sensor data rate are a little bit different). 
You can easily migrate to the right driver replacing the prefix of the functions.

Thanks for the clarification opportunity

**Comment by KiLuYa** [comment]
Thank you.
