### ISSUE TITLE
About Unico

### ISSUE THREAD

**Issue by KiLuYa** [STMicroelectronics/STMems_Standard_C_drivers#39]
To communicate with Unico, I try to implement commands on my own board as your ducument.
I met a strange thing, which may not be mentioned in the doucument.
Once I click conncet on Unico, Unico send "0x00 0x80" continously.
![image](https://user-images.githubusercontent.com/29007810/59999587-ebfc0880-9694-11e9-85b7-62eda596b1a8.png)

How should I respond to this?
I thought it should send "*setdbXXXVY" at first.
Do I miss anything?

**Comment by albezanc** [comment]
Dear KiLuYa,

I'm sorry but this is *not the right place for Unico GUI support*.

Please, refer to the links below for a complete documentation about Unico GUI and its communication Protocol:
- [Unico GUI User Manual](https://www.st.com/content/ccc/resource/technical/document/user_manual/b0/8d/9f/be/cc/2c/4e/2a/CD00297387.pdf/files/CD00297387.pdf/jcr:content/translations/en.CD00297387.pdf),
- [Professional MEMS board STEVAL-MKI109V3](https://www.st.com/en/evaluation-tools/steval-mki109v3.html#resource) resources web page. 

if other support is need please refer to [this link](https://my.st.com/cas/login?service=https://my.st.com/ols). 

I would really appreciate if we avoided replicating the titles of the issues and opening new issues on issues already present.

Thanks for understanding
