### ISSUE TITLE
Plans to add driver for LSM9DS1

### ISSUE THREAD

**Issue by silvergasp** [STMicroelectronics/STMems_Standard_C_drivers#4]
Hi, 
I am interested in using the LSM9DS1 as a component in a multi-sensor IMU run on an STM32. Are there any plans to add a C driver for this component, or would you be willing to take a pull request if I were to write one myself?
Thanks

**Comment by silvergasp** [comment]
I have done a bit of a look through the LinuxIIO drivers for this chip, and it seems that the driver could be created as a combination of the lsm6dsm_STdC and the lis3mdl_STdC drivers. Can you confirm if I am on the right track?

**Comment by albezanc** [comment]
Hi, standard C driver for lsm9ds1 will be release soon. 
Thanks for your request.

**Comment by silvergasp** [comment]
Brilliant, I look forward to hearing more

Are you able to give an ETA?

Looking at options that fit into a project timeline?

**Comment by albezanc** [comment]
planned in a couple of months

**Comment by silvergasp** [comment]
Brilliant, thankyou
