### ISSUE TITLE
Definition error in IIS3DWB Driver

### ISSUE THREAD

**Issue by pjung-bosch** [STMicroelectronics/STMems_Standard_C_drivers#40]
IIS3DWB_XL_BATCHED_AT_6667Hz
undefined at:
https://github.com/STMicroelectronics/STMems_Standard_C_drivers/blob/11f4952cadee80897f59475c05f1679dfe6bbe96/iis3dwb_STdC/driver/iis3dwb_reg.c#L2308-L2309

**Comment by albezanc** [comment]
The issue has been resolved, thanks for your contribution
