### ISSUE TITLE
LSM9DS1 false default values

### ISSUE THREAD

**Issue by MIW94** [STMicroelectronics/STMems_Standard_C_drivers#45]
Hey There,
In the libary are some defines, that doesn't fit each other.
Setting up the filters of the accelerometer with:
typedef enum {
  LSM9DS1_LP_DISABLE     = 0x00,
  LSM9DS1_LP_ODR_DIV_50     = 0x10,
  LSM9DS1_LP_ODR_DIV_100    = 0x11,
  LSM9DS1_LP_ODR_DIV_9      = 0x12,
  LSM9DS1_LP_ODR_DIV_400    = 0x13,
} lsm9ds1_xl_lp_bw_t;

doesn't match the lines
    ctrl_reg7_xl.dcf = ((uint8_t)val & 0x10U) >> 4;
    ctrl_reg7_xl.hr = ((uint8_t)val & 0x03U);

in:
int32_t lsm9ds1_xl_filter_lp_bandwidth_set(lsm9ds1_ctx_t *ctx,
                                           lsm9ds1_xl_lp_bw_t val)
{
  lsm9ds1_ctrl_reg7_xl_t ctrl_reg7_xl;
  int32_t ret;

  ret = lsm9ds1_read_reg(ctx, LSM9DS1_CTRL_REG7_XL,
                         (uint8_t*)&ctrl_reg7_xl, 1);
  if(ret == 0){
    ctrl_reg7_xl.dcf = ((uint8_t)val & 0x10U) >> 4;
    ctrl_reg7_xl.hr = ((uint8_t)val & 0x03U);
    ret = lsm9ds1_write_reg(ctx, LSM9DS1_CTRL_REG7_XL,
                            (uint8_t*)&ctrl_reg7_xl, 1);
  }
  return ret;
}

because dcf has two bits, see:

#define LSM9DS1_CTRL_REG7_XL       0x21U
typedef struct {
  uint8_t hpis1                    : 1;
  uint8_t not_used_01              : 1;
  uint8_t fds                      : 1;
  uint8_t not_used_02              : 2;
  uint8_t dcf                      : 2;
  uint8_t hr                       : 1;
} lsm9ds1_ctrl_reg7_xl_t;

So the right code must be

    ctrl_reg7_xl.hr = ((uint8_t)val & 0x10U) >> 4;
    ctrl_reg7_xl.dcf = ((uint8_t)val & 0x03U);

**Comment by albezanc** [comment]
Thanks for your contribution!
