### ISSUE TITLE
Finite State Machine submodule points to commit which is not on any branch

### ISSUE THREAD

**Issue by ojousima** [STMicroelectronics/STMems_Standard_C_drivers#46]
Hello,

The _resources/STMems_Finite_State_Machine @ 1c74d4e 
is not on any branch of the FSM project. Maybe something has been force-pushed over commits 
```
1c74d4e lsm6dsr: modified licence format
fb969ba lsm6dsox: modified licence format
2f2aba9 lsm6dso: modified licence format
```
maybe something else, but in any case it would be nice to point the submodule to some commit of the FSM master

**Comment by ojousima** [comment]
The same issue applies to Machine Learning Core commit ` 00494c8 lsm6dsox: modified licence format`

**Comment by albezanc** [comment]
You were right, the commits pointed are referred to my forks.

Thanks for your contribute.
