### ISSUE TITLE
hts221 driver throws away 3 bits of precision in temperature calibration

### ISSUE THREAD

**Issue by geoffreymbrown** [STMicroelectronics/STMems_Standard_C_drivers#52]
It appears that  your functions
hts221_temp_deg_point_0_get, hts221_temp_deg_point_1_get

discard 3 bits of precision to make the result fit in a uin8_t.  This makes absolutely no sense -- return a uint16_t  and leave it to the user to divide by 8 or return a float.

**Comment by albezanc** [comment]
This issue has been solved in the last commits.

Thank you for your contribution!
