### ISSUE TITLE
LIS2DW12: Single data conversion mode in CTRL3

### ISSUE THREAD

**Issue by masterbar** [STMicroelectronics/STMems_Standard_C_drivers#53]
Hi,

The lis2dw12 driver sets the following enum values:
```
LIS2DW12_XL_SET_SW_TRIG        = 0x32,  /* Use this only in SINGLE mode */
LIS2DW12_XL_SET_PIN_TRIG       = 0x22,  /* Use this only in SINGLE mode */
```
Then in the C file, the CTRL3 register is written like this:
```
ctrl3.slp_mode = ( (uint8_t) val & 0x30U ) >> 4;
ret = lis2dw12_write_reg(ctx, LIS2DW12_CTRL3,(uint8_t*) &ctrl3, 1);
```
This will set the SLP_MODE_SEL bit1 of CTRL3 in both cases (SW and PIN trig). But the datasheet says it shall be 0 when enabled with external trigger on INT2.

This is a bug or did I miss something?

Also the driver will assign 0x02 for the ODR (CTRL1). Why?

Thank you,
Greg

**Comment by albezanc** [comment]
Hi masterbar,

Thanks for your report, you are right, seems the issue can be fix with the follow modification:
```C
LIS2DW12_XL_SET_PIN_TRIG       = 0x12,  /* Use this only in SINGLE mode */
```
The fix will be added to the repo within the end of this week: Fri,10th January 2020.

As for the question about the ODR value: it is a fictitious value (it does not matter in single mode).

Thank you for your contribution !
