### ISSUE TITLE
LIS2DW12: conversion functions

### ISSUE THREAD

**Issue by masterbar** [STMicroelectronics/STMems_Standard_C_drivers#54]
Hi,

Why are the conversion factors used in functions `lis2dw12_from_*_to_mg` not the same as the ones in the LIS2DW12 datasheet (page 6, sensitivity values) ?

Thank you,
Greg

**Comment by albezanc** [comment]
Hi masterbar,

this issue seem the same as the issue #48. 

Please, check that answer and let me know if is valid also in this case.

Thanks for this remark.

**Comment by masterbar** [comment]
Yes, this is correct. I didn't see that the raw values were returned as 16 bits values, without being shifted to the left for 2 or 4 bits depending of the resolution.
