### ISSUE TITLE
IIS3DHHC I2C support

### ISSUE THREAD

**Issue by mateusz-** [STMicroelectronics/STMems_Standard_C_drivers#59]
Hi,

The [datasheet for IIS3DHHC](https://www.st.com/resource/en/datasheet/iis3dhhc.pdf) doesn't mention any support for I2C. However, there are some references to [I2C in example code](https://github.com/STMicroelectronics/STMems_Standard_C_drivers/blob/90ed7e12780473097d1a55b37bf2ccb97df21095/iis3dhhc_STdC/example/read_data_simple.c).

From what I can see, most drivers that support I2C have a `*_I2C_ADD_*` address define in the corresponding header file, IIS3DHHC does not.

Is I2C supported with IIS3DHHC?

**Comment by albezanc** [comment]
Its a "copy & paste" residual: as you can see spi interface is used in the example.

thanks for your warning the example will be fixed with next push.
