### ISSUE TITLE
Right-Shifting of negative signed numbers is implementation-specific

### ISSUE THREAD

**Issue by alextsam** [STMicroelectronics/STMems_Standard_C_drivers#6]
File lsm303agr_STdC/driver/lsm303agr_reg.h contains some macros for converting the raw acceleration values depending on the mode and scale such as the following:
```#define LSM303AGR_FROM_FS_2g_HR_TO_mg(lsb)  (float)((int16_t)lsb>>4)* 1.0f```
The drivers are supposed to be platform agnostic, however the shifting of signed numbers is implementation specific, as shown in the C99 standard, 6.5.7 Bitwise shift operators:
```
The result of E1 >> E2 is E1 right-shifted E2 bit positions. If E1 has an unsigned type
or if E1 has a signed type and a nonnegative value, the value of the result is the integral
part of the quotient of E1 / 2E2. If E1 has a signed type and a negative value, the
resulting value is implementation-defined.
```
(The same applies for C89 and C11). Sure, in most platforms the right shifting of negative signed numbers will act with sign extension, but I think it is better to be safe by substituting the bitwise operation with arithmetic. I made a pull request fixing this, please see https://github.com/STMicroelectronics/STMems_Standard_C_drivers/pull/5

**Comment by albezanc** [comment]
A review activity concerning the MISRA C 2012 standard is on going on all the MEMS C driver.
The MISRAC2012-Dir-4.9 warns about the risk of "Macros used like a function". 
For this reason "in-line functions" for conversion will be add in next revisions.

The new "in-line functions" will be aligned with your suggestion.

Please that the old conversion macros will be maintained for back compatibility but become recommended.

About the proposed solution please note that: no external function should be used by the sensor driver ("pow" function of "math.h" does not allowed).

Thanks very much for your contribution.
