### ISSUE TITLE
LSM6DSOX data get

### ISSUE THREAD

**Issue by YannLocatelli** [STMicroelectronics/STMems_Standard_C_drivers#62]
Hello,

I tried to use `lsm6dsox_data_get()` function in [lsm6dsox_reg.c](https://github.com/STMicroelectronics/STMems_Standard_C_drivers/blob/master/lsm6dsox_STdC/driver/lsm6dsox_reg.c#L11731)

---

I noticed that `aux_ctx` is used instead of `ctx` to read data in register 
https://github.com/STMicroelectronics/STMems_Standard_C_drivers/blob/5a189f9ccb81615c87d9ad2fb0f394cffb5853d6/lsm6dsox_STdC/driver/lsm6dsox_reg.c#L11741-L11744

---

Then later in code, register is read in a sense : temperature, accelerometer and gyroscope [[Link](https://github.com/STMicroelectronics/STMems_Standard_C_drivers/blob/master/lsm6dsox_STdC/driver/lsm6dsox_reg.c#L11754-L11804)].  
However, in the datasheet, the order of register is temperature, gyroscope and accelerometer [[Link](https://www.st.com/resource/en/datasheet/lsm6dsox.pdf#page=45)].

Inverting angular conversion with acceleration conversion seems to solve this problem.

---

I don't use ois chain, I suspect similar issue for it:

Conversion of accelerometer comes before gyroscope [[Link](https://github.com/STMicroelectronics/STMems_Standard_C_drivers/blob/master/lsm6dsox_STdC/driver/lsm6dsox_reg.c#L11819-L11868)]. It is inversed in datasheet [[Link](https://www.st.com/resource/en/datasheet/lsm6dsox.pdf#page=99)].

Then, the read of register should starts with gyroscope instead of accelerometer here: https://github.com/STMicroelectronics/STMems_Standard_C_drivers/blob/5a189f9ccb81615c87d9ad2fb0f394cffb5853d6/lsm6dsox_STdC/driver/lsm6dsox_reg.c#L11806-L11816
(`LSM6DSOX_SPI2_OUTX_L_G_OIS` should replace `LSM6DSOX_SPI2_OUTX_L_A_OIS`)

**Comment by albezanc** [comment]
Thanks for your valuable contribution, the fixes related to this issue will be published within this week.
