### ISSUE TITLE
Incorrect operator in LSM9DS1 reset polling function

### ISSUE THREAD

**Issue by bytestuff** [STMicroelectronics/STMems_Standard_C_drivers#64]
Hi,

The function used for polling reset completion should use the | operator to combine the reset flags. In its present form, the *val value will be zero even if one of the sensors is still under reset. This does not appear to be the desired function behaviour based on the example usage.

https://github.com/STMicroelectronics/STMems_Standard_C_drivers/blob/49a122e02e33405ce9f8aea0cd9f215582b2d720/lsm9ds1_STdC/driver/lsm9ds1_reg.c#L1242

**Comment by albezanc** [comment]
For sure, thank you very much for your contribution!
