### ISSUE TITLE
LSM9DS1 Self-test Correction

### ISSUE THREAD

**Issue by lle** [STMicroelectronics/STMems_Standard_C_drivers#69]
It appears that there is a correction needed for the LSM9DS1 selftest example at Line 129
https://github.com/STMicroelectronics/STMems_Standard_C_drivers/blob/master/lsm9ds1_STdC/example/lsm9ds1_self_test.c

Current:
`static sensbus_t imu_bus = {&SENSOR_BUS,                            LSM9DS1_MAG_I2C_ADD_L,                            0,                           0};`
`static sensbus_t mag_bus = {&SENSOR_BUS,                           LSM9DS1_IMU_I2C_ADD_H                            0,                            0};`

I believe should be:
`static sensbus_t imu_bus = {&SENSOR_BUS,                            LSM9DS1_IMU_I2C_ADD_H,                            0,                            0};`
`static sensbus_t mag_bus = {&SENSOR_BUS,                            LSM9DS1_MAG_I2C_ADD_L,                           0,                            0};`

**MAG**_I2C_ADD and **IMU**_I2C_ADD are inverted

**Comment by albezanc** [comment]
Absolutely right!
Thanks very much for your contribution
