### ISSUE TITLE
LSM9DS1 I2C Address 8bit Format - Change Request

### ISSUE THREAD

**Issue by lle** [STMicroelectronics/STMems_Standard_C_drivers#70]
I was reading through the datasheet page 30, table 20; I believe there is a fix needed for 
https://github.com/STMicroelectronics/STMems_Standard_C_drivers/blob/master/lsm9ds1_STdC/driver/lsm9ds1_reg.h

on Line 127
`/** I2C Device Address 8 bit format  if SA0=0 -> 0x3D if SA0=1 -> 0x39 **/`
`#define LSM9DS1_MAG_I2C_ADD_L      0x3DU`
`#define LSM9DS1_MAG_I2C_ADD_H      0x39U`

should be:
`#define LSM9DS1_MAG_I2C_ADD_L      0x39U`
`#define LSM9DS1_MAG_I2C_ADD_H      0x3DU`

Addresses are inverted

**Comment by albezanc** [comment]
Absolutely right!
Thanks very much for your contribution
