### ISSUE TITLE
LSM6DSOX self test "xl" vs "gy" typos

### ISSUE THREAD

**Issue by jtrovato** [STMicroelectronics/STMems_Standard_C_drivers#72]
I believe that there are a couple typos in lsm6dsox_STdC/example/lsm6dsox_self_test.c, specifically during the gyro section of the self-test there are a couple of accelerometer functions called.

on line 281 `lsm6dsox_xl_flag_data_ready_get(&dev_ctx, &drdy);`
on line 306 `lsm6dsox_xl_flag_data_ready_get(&dev_ctx, &drdy);`
on line 335 `lsm6dsox_xl_data_rate_set(&dev_ctx, LSM6DSOX_GY_ODR_OFF);`

I had to change all of the "lsm6dsox_xl_..." to "lsm6dsox_gy_..." to get the test to complete successfully. Without these changes, the test loops forever waiting for a accelerometer data ready flag.

**Comment by albezanc** [comment]
Absolutely right!
Thanks very much for your contribution
