### ISSUE TITLE
Bug: LSM6DSOX FIFO tag getter

### ISSUE THREAD

**Issue by vnerozinea** [STMicroelectronics/STMems_Standard_C_drivers#74]
In [lsm6dsox_fifo_sensor_tag_get](https://github.com/STMicroelectronics/STMems_Standard_C_drivers/blob/master/lsm6dsox_STdC/driver/lsm6dsox_reg.c#L6148) missed case for timestamp:

```
    case LSM6DSOX_TIMESTAMP_TAG:
      *val = LSM6DSOX_TIMESTAMP_TAG;
      break;
```

**Comment by albezanc** [comment]
Thanks a lot for your contribution!
