### ISSUE TITLE
Incorrect conditional causes infinite loop

### ISSUE THREAD

**Issue by siddhantmodi** [STMicroelectronics/STMems_Standard_C_drivers#79]
EDIT: Device is LSM9DS1 and the file I am talking about is the [self_test example](https://github.com/STMicroelectronics/STMems_Standard_C_drivers/blob/master/lsm9ds1_STdC/example/lsm9ds1_self_test.c).

In line 329, when the loop is checking to see if new data is available, the following conditional is used:

`while(reg.status_imu.xlda)`

it should instead be:

`while(!reg.status_imu.xlda)` 

Line 319 has done this correctly.

The same problem exists on Lines 239 and 419: 

(239): `while(reg.status_mag.zyxda)`
(419): `while(reg.status_imu.gda)`

These two statements should have the `!` applied to them too.

**Comment by albezanc** [comment]
**Thank you for your contribution!** 
The example was now fixed.
