### ISSUE TITLE
Incorrect unit for the gyro self-test values in Example for LSM9DS1

### ISSUE THREAD

**Issue by siddhantmodi** [STMicroelectronics/STMems_Standard_C_drivers#80]
In the [LSM9DS1 self_test example](https://github.com/STMicroelectronics/STMems_Standard_C_drivers/blob/master/lsm9ds1_STdC/example/lsm9ds1_self_test.c), the self-test values for the gyroscope are as following:

`/* Self test limits in mdps @ 2000 dps*/
static const float min_st_gy_limit[] = {200.0f, 200.0f,  200.0f};
static const float max_st_gy_limit[] = {800.0f, 800.0f, 800.0f};`

However, I believe that these numbers are in `dps` rather than in `mdps`. [This ](https://www.st.com/resource/en/datasheet/lsm6ds3.pdf) datasheet for the LSM6DS3 shows the self-test limits for the gyro to be in the range of 150-700 `dps`. If you look at the [self-test example](https://github.com/STMicroelectronics/STMems_Standard_C_drivers/blob/master/lsm6ds3_STdC/example/lsm6ds3_self_test.c) for the LSM6DS3, lines 100 and 101 show that these numbers have been multiplied by 1000 to bring them to the mdps unit.

I therefore argue that the same should be done for the LSM9DS1 too. I have run the self-test on my platform and the test is failing unless the numbers are converted to mdps from dps.

**Comment by albezanc** [comment]
**Thank you for your contribution!** 
The example was now fixed.
