### ISSUE TITLE
Wrong values in "lsm6dsox_start_config_t"

### ISSUE THREAD

**Issue by vnerozinea** [STMicroelectronics/STMems_Standard_C_drivers#83]
It looks like in [this enum](https://github.com/STMicroelectronics/STMems_Standard_C_drivers/blob/bde2bc99b9bd8a6b474f41187dff1c9f8985aeb5/lsm6dsox_STdC/driver/lsm6dsox_reg.h#L2799) values are wrong.

From doc:
> START_CONFIG bit selects the sensor hub trigger signal.
> – When this bit is set to 0, the accelerometer/gyroscope sensor has to be active (not in Power-Down mode) and the sensor hub trigger signal is the accelerometer/gyroscope data-ready signal, with a frequency defined by the SHUB_ODR_[1:0] bits of the SLAVE0_CONFIG register (up to 104 Hz).
> – When this bit is set to 1, at least one sensor between the accelerometer and the gyroscope has to be active and the sensor hub trigger signal is the INT2 pin. In fact, when both the MASTER_ON bit and START_CONFIG bit are set to 1, the INT2 pin is configured as an input signal. In this case, the INT2 pin has to be connected to the data-ready pin of the external sensor (Figure 21. External sensor connections in Mode 2) in order to trigger the read/write operations on the external sensor registers. Sensor hub interrupt from INT2 is ‘high-level triggered’ (not programmable).

**Comment by albezanc** [comment]
Sure! Thank you for your contribution!
