### ISSUE TITLE
LSM6DSOX_SLV1_CONFIG in "lsm6dsox_sh_data_rate_set"

### ISSUE THREAD

**Issue by vnerozinea** [STMicroelectronics/STMems_Standard_C_drivers#84]
Why are using "slave1" [there](https://github.com/STMicroelectronics/STMems_Standard_C_drivers/blob/bde2bc99b9bd8a6b474f41187dff1c9f8985aeb5/lsm6dsox_STdC/driver/lsm6dsox_reg.c#L8941)? 
According to documentation ODR bits are only in Slave 0 register 0x17.

**Comment by albezanc** [comment]
Sure! Thank you for your contribution!
