### ISSUE TITLE
LIS2DE12 Wrong values for lis2de12_sdo_pu_disc_t PULL-UP

### ISSUE THREAD

**Issue by lukas-k** [STMicroelectronics/STMems_Standard_C_drivers#85]
According to the datasheet (ST DocID027326 Rev 2) the bit values for connecting/disconnecting the internal pull-up resistor on Pin SDO/SA0 are (CTRL_REG0 1Eh):

- 0: pull-up connected
- 1: pull-up disconnected

In contrast, the enum typedef in lis2de12_reg.h is written as:
`typedef enum {
  LIS2DE12_PULL_UP_DISCONNECT  = 0,
  LIS2DE12_PULL_UP_CONNECT     = 1,
} lis2de12_sdo_pu_disc_t;`

The values should be interchanged.

**Comment by albezanc** [comment]
Sure! Thank you for your contribution!
