### ISSUE TITLE
Error variable is overwritten.

### ISSUE THREAD

**Issue by erk1313** [STMicroelectronics/STMems_Standard_C_drivers#9]
mm_error is overwritten by second operation.  Needs an if statement.

`int32_t lsm6dsm_spi_mode_set(lsm6dsm_ctx_t *ctx, lsm6dsm_sim_t val)
{
  lsm6dsm_reg_t reg;
  int32_t mm_error;

  mm_error = lsm6dsm_read_reg(ctx, LSM6DSM_CTRL3_C, &reg.byte, 1);
  reg.ctrl3_c.sim = val;
  mm_error = lsm6dsm_write_reg(ctx, LSM6DSM_CTRL3_C, &reg.byte, 1);

  return mm_error;
}
`

**Comment by albezanc** [comment]
A review activity concerning the MISRA C 2012 standard is on going on all the MEMS C driver. 
This issue will be solved with MISRA compliant version. 
Thanks for your contribution.
