### ISSUE TITLE
ism303dac driver - ism303dac_xl_act_sleep_dur_set() wrong register

### ISSUE THREAD

**Issue by namnequam** [STMicroelectronics/STMems_Standard_C_drivers#90]
Hello,

there is a typo in the ism303dac_STdC driver. Functions ism303dac_xl_act_sleep_dur_set/get use wrong register name (ISM303DAC_WAKE_UP_THS_A instead of ISM303DAC_WAKE_UP_DUR_A).

Thank you.

**Comment by albezanc** [comment]
Sure! Thanks for your contribution!
