### ISSUE TITLE
LSM6DSR pitch, roll and yaw measurements

### ISSUE THREAD

**Issue by TinManAkshay** [STMicroelectronics/STMems_Standard_C_drivers#91]
Hi,
I am Akshay and my employer is going to use this IMU in our custom PCBs for the pitch, roll and yaw observations. I looked at both the datasheet as well as the respective drivers like which registers and functions are being used to estimate pitch, roll and yaw values. In the datasheet, registers OUTX_L_G (22h) and OUTX_H_G (23h) are mentioned to get the raw values and so on for other IMU's parameters. 
However, in lsm6dsr_reg.c under the drivers, I cannot see any function other than the one which has OUTX_L_G being used. Since pitch value is expressed in 16-bit word, I don't know how to get the value from OUTX_H_G.
Can somebody give me insights (in terms of programming) on how i can get the pitch, roll and yaw values, if I am using these drivers? I'd appreciate all the support. 

Thanks,
Akshay

**Comment by albezanc** [comment]
Hi Akshay, please look at [this example](https://github.com/STMicroelectronics/STMems_Standard_C_drivers/blob/master/lsm6dsr_STdC/example/read_data_simple.c), it should be match your needs.

Thanks for the opportunity to clarify.
