### ISSUE TITLE
LSM6DSOX sensor hub code with LIS2MDL

### ISSUE THREAD

**Issue by mmadela** [STMicroelectronics/STMems_Standard_C_drivers#93]
Hi,
apparently the lsm6dsox_sensor_hub_fifo_lis2mdl_timestamp_simple.c was never tested,
no correct data from slave sensor are read
the address of the slave sensor is wrong (it must be given in 7bit format not the 8bit)
the SPI variant (MKI109V2) never enters the loop because interrupt mock routine returns wrong value
and code with activated INT1 even does not compile

[0001-fix.txt](https://github.com/STMicroelectronics/STMems_Standard_C_drivers/files/5437508/0001-fix.txt)

BR

**Comment by albezanc** [comment]
Sorry for the inconvenience caused to you, and thanks very much for your contribution.
