### ISSUE TITLE
Arduino libraries for LSM6DSR

### ISSUE THREAD

**Issue by TinManAkshay** [STMicroelectronics/STMems_Standard_C_drivers#96]
Hi,

I have got this LSM6DSR breakout board (https://www.digikey.com/en/products/detail/stmicroelectronics/STEVAL-MKI194V1/10078018) and I have adafruit M4 express board which has SAMD51 MCU. Does any have any idea which arduino library I can use to get the raw values from the accelerometer. I hope there will be one arduino library.

Thanks,
Akshay

**Comment by albezanc** [comment]
Hi Akshay,

you can find the arduino driver [here](https://github.com/stm32duino/LSM6DSR).

thanks for the clarification opportunity!
