### ISSUE TITLE
Bug with lis3mdl_int_config_set()

### ISSUE THREAD

**Issue by uilter** [STMicroelectronics/STMems_Standard_C_drivers#99]
Hi, I was testing the lib for lis3mdl and found a mistake into lis3mdl_int_config_set function.
This function need to write into register LIS3MDL_INT_CFG, the current version is reading.

`/**
  * @brief  Interrupt configuration register[set]
  *
  * @param  ctx      read / write interface definitions(ptr)
  * @param  val      Registers INT_CFG(ptr)
  * @retval          interface status (MANDATORY: return 0 -> no Error)
  *
  */
int32_t lis3mdl_int_config_set(stmdev_ctx_t *ctx, lis3mdl_int_cfg_t *val)
{
  //return lis3mdl_read_reg(ctx, LIS3MDL_INT_CFG, (uint8_t*) val, 1);
  return lis3mdl_write_reg(ctx, LIS3MDL_INT_CFG, (uint8_t*) val, 1);
}`

**Comment by albezanc** [comment]
Thank you for your contribution, really appreciated!
